### ISSUE TITLE
iOS Simulator: Text sometimes gets cut off

### ISSUE THREAD

**Issue by larsmango** [Framstag/libosmscout#462]
I have been using libosmscout in the iOS simulator and I was experiencing some strange behaviors when it comes to text:
In many cases the text will be cut off which does not look nice.

Has anyone else seen this? I didn't find any duplicate bugs on this here on GitHub.

**Comment by Framstag** [comment]
Can you add a picture, possible with some markers, that visualize the problem?

**Comment by Framstag** [comment]
This is possible a know problem if rendering tiles. A screenshot would help us seeing if you are speaking of that known effect.

**Comment by larsmango** [comment]
@Framstag Here are three screenshots of this effect from different zoom levels:
![bug_cut_map](https://user-images.githubusercontent.com/31371712/29803763-f1bef4c6-8c32-11e7-9563-a7ec3bf97e6a.png)
As you can see, the title of the mountain sometimes gets cut off, but the amount of letters that is cut off varies between different zoom levels.

If this is a duplicate, could you assign the duplicate issue here so I can see what the current state of this is and what the technical difficulties are?

Thanks!

**Comment by larsmango** [comment]
Option three only seems to be a temporary solution (making the text smaller).
Sometimes it is necessary to display labels with a larger font (or the name of the item ist just long).

It would be great if the renderer could support text over multiple tiles.

Is this an iOS specific problem or is this affecting all platforms?

**Comment by Karry** [comment]
Hi. This is common problem with tiled rendering (it exists with libosmscout/Qt, Mapnik...). We partialy solve it (in Qt) by loading larger area and compute layout for all labels (even for objects outside visible area). But this solution is expensive for higher zoom levels with many labels - so we disable it (Qt again) for zoom > 16 (?). Faster label layouter (with caching?) would help with it... I am not sure how iOS renderer is configured, but I guess that it uses similar tradeoff.

**Comment by vyskocil** [comment]
Actually in the iOS demo app the data is only fetched for the tile size, there is no meta-tile rendering.
But I just pushed a pull request for multi-line label rendering for iOS that should help with large multi-word labels.

**Comment by Framstag** [comment]
Cool. Note that the tiler demo does use the meta-tile or super-tile approach and corresponding code could in principle be copied.

**Comment by Framstag** [comment]
Is this issue thus still valid? Can we close it?

**Comment by Framstag** [comment]
Closing the issue.

**Comment by frogg** [comment]
I would like to re-open this issue, because this is still a problem for me, not only on the simulator, also on an actual iOS device.
The screenshot is an extreme case, because district names are somehow rendered in very large type (I assume that‘s the default behavior of the `standard.oss`?). However, also many street names are cut off at the intersection of tiles.

![IMG_8A1D67E431C9-1](https://user-images.githubusercontent.com/5204169/129618348-8244695f-6ee1-428a-91dd-3afe59096e67.jpeg)

**Comment by vyskocil** [comment]
I switched from tile rendering to full screen rendering long time ago and this solved these issues (hopefully ;-) I had to implement a moving map component but it is failing to compete with Apple’s MapKit speed, fluidity and functionalities… I now think about going back to tile rendering using again the MKMapView component with custom tiles rendered by OSMScout…
So I’ll look again at metatile rendering, I think the lib should support it natively.

**Comment by pl4tonoff** [comment]
Thank you, cutting out the tile from a large image did significantly improve the result, but in some situations the problem remained. This is more often seen in large fonts. However, this approach has significantly affected performance
![Screenshot 2021-10-13 104048](https://user-images.githubusercontent.com/66258410/137091428-c6de70f6-9cb3-4e24-85c0-4d770d72cd06.png)
![Screenshot 2021-10-13 105144](https://user-images.githubusercontent.com/66258410/137091463-94369640-9c7d-4bbe-9acd-62ea8b03091e.png)

.

**Comment by vyskocil** [comment]
As we draw labels from left to right and top to down maybe the border don't have to extend to the right and bottom (at the right of the tiles and below the last row of tiles).
But If we support RTL languages it won't be the case.

**Comment by Framstag** [comment]
I try to summarize:

OSMScout has two modus o rendering:
* Tile based (the visible area is a composition of multiple rendered tiles of equal size)
* Full screen rendering (the visible area is rendered in one go)

There are advantages and disadvantages for both solution, but for the problem above both solution are similar.

Normally all objects are draw if they are visible, else they are not drawn. Visibility is calculated *by the renderer based on the passed data* based on the outline of the object, taking into account effects of style sheet options.

IF I only pass data for half of the area, the renderer draws only half of the area, if I pass data for more than the visible area, the renderer will drop invisible data (though there is a flag to skip this!). This is a performance optimization.

As Karry mentioned the label layouter will also take into account objects outside the visible area,

The problem arises if we have objects that renderer outside their bounding box (a problem that have all box based renderers for example most UIs will have this problem, too). This is the case for overlay labels.

There re two options:
* Do no make use of overlay labels
* Make use of overlay images. In consequence:
  * Load data outside the visible area
  * Make the renderer draw objects (in this case only labels!) outside the visible area. 

Some further comments:
* You do not have to load all data outside the visible rectangle. You only need to load data (of type) that has overlay labels. This can be calculated on runtime by analyzing the style sheet.
* For rendering overlay labels outside the visible area you only need to know their position, you do not need to know the bounding box or the actual outline of the object. This means we could write a specialized index that only stores the object type together with the label to further optimize retrieving label outline information (and I assume that the number of objects with outline labels is low anyway).
* The renderer does not need to render things in one go. You can pass different data to the label rendering step than to the other steps (though it does some caching, which would make things more complicated).

**Comment by Karry** [comment]
@pl4tonoff labels are rotated when you are using "plane" rendering with QML component. But not with tiled one. 

Render labels on top of the tiles is interesting idea. You can render map without labels when using some low-level api, but not with the QML one... But now, I am a bit confused - QML map component don't allow tilt and I was expecting that we are discussing iOS backend...

**Comment by pl4tonoff** [comment]
Please let me know if you manage to minimize text cutting for rendering only one tile. Rendering a large image for each tile had a bad effect on performance, although it helped solve most of this problem.
