### ISSUE TITLE
Import of South America failed : Cannot write coordinate: Delta between coordinates too big

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#498]
I tried to import the file latest south-america-latest.osm.pbf from Geofabrik with the current command line but It failed : 

`Import --destinationDirectory . --bounding-polygon ../south-america-latest.poly ../south-america-latest.osm.pbf > import.log 2>&1
`

with this logs : 

```
...
 - Optimizing type boundary_country_maritime...
   Optimized from 23 to 1 areas
   Writing map for level 2, index level 5, 1 cells, 1 entries, 7 B
   Optimized from 23 to 1 areas
   Writing map for level 3, index level 5, 1 cells, 1 entries, 7 B
   Optimized from 23 to 2 areas
   Writing map for level 4, index level 5, 4 cells, 4 entries, 111 B
   Optimized from 23 to 22 areas
   Writing map for level 5, index level 5, 14 cells, 30 entries, 253 B
   Optimized from 23 to 23 areas
   Writing map for level 6, index level 5, 15 cells, 31 entries, 258 B
   Optimized from 23 to 23 areas
   Writing map for level 7, index level 5, 15 cells, 31 entries, 260 B
   Optimized from 23 to 23 areas
   Writing map for level 8, index level 5, 15 cells, 31 entries, 260 B
   Optimized from 23 to 23 areas
   Writing map for level 9, index level 5, 15 cells, 31 entries, 273 B
   Optimized from 23 to 23 areas
   Writing map for level 10, index level 5, 15 cells, 31 entries, 273 B
 - Optimizing type boundary_country...
   Optimized from 26 to 6 areas
   !! File './areasopt.dat' - Cannot write coordinate: Delta between coordinates too big
Automatically closing FileScanner for file './areas.dat'!
   !! Error while optimizing areas
Automatically closing FileWriter for file './areasopt.dat'!
   => 43.836s
   !! Error while executing step 'OptimizeAreasLowZoomGenerator'!
+ Summary...
   !! Import failed!

```

**Comment by Framstag** [comment]
The reason is, that the import (likely) does contains objects (in this case areas), where the geographical distance between individual nodes of the area is too big. The file format imposes a limit. I take a look. The importer should test for this and just skip the concrete area in this case. It should also write a better error message in this case.

**Comment by Framstag** [comment]
I was not able to reproduce the problem (Possibly the export changed/was fixed , I also skipped passing *.poly, so this might also have some influence). Nevertheless I tried to add a check and a fix. Please test again.

**Comment by vyskocil** [comment]
I updated the code and did the same test with the same pbf file : 

```
 - Optimizing type boundary_country...
   !! Area coordinates are not dense enough to be written for area 167520447
   !! Area coordinates are not dense enough to be written for area 365961659
   !! Area coordinates are not dense enough to be written for area 366472415
   Optimized from 26 to 6 areas
   !! File './areasopt.dat' - Cannot write coordinate: Delta between coordinates too big
Automatically closing FileScanner for file './areas.dat'!
   !! Error while optimizing areas
Automatically closing FileWriter for file './areasopt.dat'!
   => 36.676s
   !! Error while executing step 'OptimizeAreasLowZoomGenerator'!
+ Summary...
   !! Import failed!
```
I'm now downloading the new release of south-america.osm.pbf and will try again...

**Comment by vyskocil** [comment]
I got the same results with the up to date pbf file !
I'll try without the poly file...

**Comment by vyskocil** [comment]
I got the same results with the up to date pbf file !
I'll try without the poly file...

**Comment by vyskocil** [comment]
I still reproduce the issue with the up to date south-america.osm.pbf and this command line : 

`Import --destinationDirectory . ../south-america-latest.osm.pbf > import.log 2>&1`

**Comment by Framstag** [comment]
The error messages are the result of my changes. But it seem like there is another place in the code, where vector<Coord> is written.

`!! Area coordinates are not dense enough to be written for area 167520447`

I keep investigating.

**Comment by Framstag** [comment]
I still can not reproduce the bug. Interestingly I also do not get the warning  that areas have been skipped because of "too big delta". Calling Import with default arguments as suggested, also does not reproduce the problem. Something is strange. 

Wait, on my system boundary_country will not be optimized! Is it possible that you added the OPTIMIZE_LOW_ZOOM flag to the map.ost locally? I'll add this flag locally, too, and see what happens.

**Comment by Framstag** [comment]
Now that I can reproduce the issue, the fix was 30 seconds (and shameful for me). Please test again and close the issue if fixed. The import should now run through, though some areas will be dropped.

**Comment by vyskocil** [comment]
Yes it works ! No, you aren't stupid ;-)
